### PR TITLE
Add a scrapd2to3 script

### PR DESCRIPTION
**Pull request by rgreinho**
Adds a script to convert the ScrAPD 2 entries to their ScrAPD 3
equivalent.

Drive by:
* Update the scrapd-merge CLI description.

### CODE REVIEW

**Comment by mscarey** [comment]
This script looks like it will depend on the phenomenon of labels like "Deceased 1:" resulting in `scrapd` creating field labels like "1" because `scrapd` creates the field name from the word that ends with a colon. But that was a bug that you couldn't have anticipated when you wrote that part of the scraper. There hadn't yet been any bulletins published with labels like "Deceased 1:". There was a prior multi-fatality bulletin, but it had the label "Deceased:" followed by both entries, which means `scrapd` was expected to assign the label `Deceased` even if there were multiple fatalities. In my PR https://github.com/scrapd/scrapd/pull/184, "Deceased" fields are always labeled "Deceased", not "1" or "2".

Also, the word "Deceased" is part of the value of one of the fields in SCRAPD2_ENTRY_JSON. But that's exactly the same bug as https://github.com/scrapd/scrapd/issues/183, which I fixed in https://github.com/scrapd/scrapd/pull/184. Even if you do want to write a migration from the old format to a new format, wouldn't it make sense to have the migration start with a version of the data that incorporates my bugfixes?

**Comment by rgreinho** [comment]
Ahhhh, you're too quick, you were not supposed to review it yet! That's why I had not assign you yet 😁 

So, yes, you're absolutely right, this should come after we incorporate your bug fixes. That's why it is item 4 on list in the meta issue scrapd/scrapd#191. I just had time this morning and I wanted to play with the idea of adding data models using dataclasses, that's why I started this. Therefore this may not be the final version, but a close idea of it nonetheless.

Regarding the first part of your review, no the migration script does not use the `1:` or `2:`, it actually ignores them. Look at the  `from_dict()` function of the ScrAPDEntry class and you'll see the fields that are used to populate the data class. Using data classes would have the benefit to prevent having unwanted extra fields in the data set.

Anyway, let's postpone the review until we complete the other tasks. Once we're there you could review it (again).

**Comment by rgreinho** [comment]
It is now up for review @mscarey! 

It uses the models and utility functions from `scrapd`.

**Comment by rgreinho** [comment]
Merging to move forward with the work on the pipeline. Re-open the associated issue in case of problem.

**Pull request merged**
